# Generated by Django 4.2.10 on 2024-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.IntegerField(),
        ),
    ]
