# Generated by Django 4.2.10 on 2024-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_gallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourse',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
