# Generated by Django 4.2.10 on 2024-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0007_teacher_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_login',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
