# Generated by Django 4.2.10 on 2024-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0008_teacher_login_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
