# Generated by Django 4.2.10 on 2024-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0009_teachers_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='education',
        ),
    ]
